### ISSUE TITLE
Request:  Incremental Search on Xojo ListBox

### ISSUE THREAD

**Issue by JMichaelTX** [tempelmann/XojoListboxTV#2]
Thomas,

Looks like you have some great stuff here for Xojo.  Thanks again for steering me towards Xojo in the Late Night forum.

Since you have done so much with the Xojo ListBox here, I'm wondering if you have developed an incremental search method?  That is actually one of my most important use cases.

It's too bad that your free stuff requires a substantial investment in the MBS Plugins.  I can't tell for sure but it looks like about $300.  Too much for me to spend now, given I haven't even bought a license for Xojo.

**Comment by tempelmann** [comment]
I've also made quite a few free things that don't rely on MBS. But this one does.

Not sure what you mean by incremental search. You mean that you want to be able to search in a listbox, where the user enters part of the search string, and the list updates live? If you only have a few 100s or 1000s of rows, you can simply re-fill the standard Xojo Listbox from scratch every time (RemoveAllRows, then AddRow). But if you have 10000s of rows, this will become rather slow when the user types the first char or clears the search again.

An cheap alternative to using this NSTableView based listbox would be to fake a large one by using a non-scrolling Listbox and then place your own vertical Scrollbar next to it, and then use it like a dynamic listbox. There is an example of this on Xojo's blog: https://blog.xojo.com/2020/04/17/lazy-loading-data-with-listbox/

**Comment by tempelmann** [comment]
An incremental search is fairly easy to do:

1. Add both a TextField and a Timer to the window.
2. Make a method that rebuilds the entire ListBox, but also checks an optional filter variable (set from the TextField's Text property - don't invoke this every time in the loop, as it'll slow things down - use a local variable that holds a copy of the string instead): If it's non-empty, then check with InStr() if the to-be-added rows match the filter string and only add them if they match.
3. Set the Timer's Period to 300 ms and Mode to Off (0).
4. In the Timer's Action event, put code that will rebuild the list (with applying the filter if it's non-empty)
5. In the TextField's TextChanged event, Reset the timer (so that it won't fire soon if it's already running) and set its Mode to Single (1) in order to restart it.
6. In the TextField's KeyDown event, check for typed Return and Enter keys (`if key.asc=3 or key.asc=13 then`) and then stop the timer (Mode=0), rebuild the list with the filter immediately, and `return true` so that the Return key doesn't become part of the TextField's content.

That way, if the user types, the list will either update after 0.3s automatically, or immediately if the user types Return.

**Comment by JMichaelTX** [comment]
> An incremental search is fairly easy to do:

Thanks Thomas.  That looks very interesting.  I would never have thought of that method using a Timer.  I'll give it a shot.

One thought did occur to me:  There is no need to actually populate the ListBox with all of the (2,000+) entries.  All I need to do is show a reasonable number (~100) but do the search on the entire underlying array (or maybe text).

My source data is text with one line per item.  I was wondering if using RegEx on the text source might be the fastest to find the lines that match?  And then use those lines to show in the ListBox.

**Comment by tempelmann** [comment]
If you can come up with a RegEx for that, yes. It'll have to give you the complete lines so that you can then add them. Problem with Regex is, however, that you need to modify the user's input, e.g. escape the chars. You could simply escape EVERY char with "\", like so:

```
dim input as String = TextField1.Text
dim asChars() as String = input.Split("") // split into chars
dim escaped as String = "\" + Join (asChars, "\")
```

Now you can use the escaped string in a Regex, such as:

```
dim regexFindString as String = "^(.*"+escaped+".*)$"
```

That find string should find the text in any line and then return the entire line as the first match.

Alternatively, split the text into an array of lines, and search them with InStr:

```
dim allText as String = ... // the text you want to search
dim lines() as String = ReplaceLineEndings(allText,EndOfLine).Split(EndOfLine)
for each line as String in lines
  if line.InStr (searchText) > 0 then
   Listbox1.AddRow line
next
```
